name: Preview

on:
  push:
    branches:
      - preview/**
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/cache/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build Jekyll site
        run: |
          mv docker-compose.ci.yml docker-compose.override.yml
          docker-compose run --rm web /bin/bash -c "(bundle check || bundle install --jobs=3) && bundle exec jekyll build"
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.NOW_ORG_ID }}
          now-project-id: ${{ secrets.NOW_PROJECT_ID }}
          working-directory: ./build
